apiVersion: v1
kind: ServiceAccount
metadata:
  name: lcc-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lcc-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lcc-role-binding
subjects:
  - kind: ServiceAccount
    name: lcc-service-account
roleRef:
  kind: Role
  name: lcc-role
  apiGroup: rbac.authorization.k8s.io
