version: 2.1

parameters:
  lcc-opa-url:
    type: string
    default: ""
  lcc-opa-token:
    type: string
    default: ""
  lcc-redis-url:
    type: string
    default: ""

orbs:
  lcc: ./orb.yml

workflows:
  license-compliance:
    jobs:
      - lcc/scan:
          name: lcc-scan
          policy: permissive
          context: saas
          threshold: '0.7'
