from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from lcc.detection.gradle import GradleDetector


BUILD_GRADLE = """
plugins {
    id 'java'
}

dependencies {
    implementation "org.apache.commons:commons-lang3:3.12.0"
    testImplementation(group: "junit", name: "junit", version: "4.13.2")
}
"""

GRADLE_LOCK = """
# This file is generated by Gradle.
org.apache.commons:commons-lang3:3.12.0=compileClasspath
junit:junit:4.13.2=testCompileClasspath
"""


class GradleDetectorTests(unittest.TestCase):
    def test_detects_dependencies(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            root = Path(tmp_dir)
            (root / "build.gradle").write_text(BUILD_GRADLE, encoding="utf-8")
            (root / "gradle.lockfile").write_text(GRADLE_LOCK, encoding="utf-8")

            detector = GradleDetector()
            components = detector.discover(root)
            names = {component.name for component in components}

            self.assertIn("org.apache.commons:commons-lang3", names)
            self.assertIn("junit:junit", names)


if __name__ == "__main__":
    unittest.main()
